# Generated by Django 6.1 on 2026-08-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('category', models.CharField(default='Uncategorized', max_length=100)),
                ('is_anomaly', models.BooleanField(default=False)),
            ],
        ),
    ]
