# Generated by Django 6.1 on 2026-10-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_api', '0002_alter_transaction_amount_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('monthly_cap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_month', models.CharField(default='2026-09', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
