# Generated by Django 6.1 on 2026-10-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_api', '0003_categorybudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybudget',
            name='target_month',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='categorybudget',
            unique_together={('category', 'target_month')},
        ),
    ]
